export const sampleData = {
  personalInfo: [
    {
      name: "name",
      type: "text",
      key: "name",
      val: "Name",
      placeholder: "Enter Your Name",
      label: "Full Name",
    },
    {
      name: "phone",
      type: "tel",
      key: "phone",
      val: "(123) 456-7890",
      placeholder: "Enter Phone Number",
      label: "Phone Number",
    },
    {
      name: "email",
      type: "email",
      key: "email",
      val: "myEmail@gmail.com",
      placeholder: "Enter Email",
      label: "Email",
    },
    {
      name: "location",
      type: "text",
      key: "location",
      val: "San Diego, CA",
      placeholder: "Enter Your Location",
      label: "Location",
    },
  ],
  education: [
    [
      {
        name: "schoolName",
        type: "text",
        key: "schoolName",
        val: "UCSD",
        placeholder: "School Name",
        label: "School",
      },
      {
        name: "degree",
        type: "text",
        key: "degree",
        val: "Bachelor in Data Science",
        placeholder: "Degree",
        label: "Degree",
      },
      {
        name: "location",
        type: "text",
        key: "location",
        val: "San Diego, CA",
        placeholder: "Location",
        label: "Location",
      },
      {
        name: "startDate",
        type: "text",
        key: "startDate",
        val: "09/2020",
        placeholder: "Start Date",
        label: "Start Date",
      },
      {
        name: "endDate",
        type: "text",
        key: "endDate",
        val: "06/2024",
        placeholder: "End Date",
        label: "End Date",
      },
    ],
  ],

  newSchool: [
    {
      name: "schoolName",
      type: "text",
      key: "schoolName",
      val: "Orange Coast College",
      placeholder: "School Name",
      label: "School",
    },
    {
      name: "degree",
      type: "text",
      key: "degree",
      val: "Associate in Arts",
      placeholder: "Degree",
      label: "Degree",
    },
    {
      name: "location",
      type: "text",
      key: "location",
      val: "Costa Mesa, CA",
      placeholder: "Location",
      label: "Location",
    },
    {
      name: "startDate",
      type: "text",
      key: "startDate",
      val: "08/2014",
      placeholder: "Start Date",
      label: "Start",
    },
    {
      name: "endDate",
      type: "text",
      key: "endDate",
      val: "06/2016",
      placeholder: "End Date",
      label: "End",
    },
  ],

  experience: [
    [
      {
        name: "company",
        type: "text",
        key: "company",
        val: "Facebook",
        placeholder: "Company",
        label: "Company",
      },
      {
        name: "position",
        type: "text",
        key: "position",
        val: "Software Engineer",
        placeholder: "Position",
        label: "Position",
      },
      {
        name: "description",
        type: "textarea",
        key: "description",
        val: "Make Zuck rich. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, architecto unde, quidem magnam sint consequatur, incidunt sit itaque delectus culpa possimus excepturi iusto. Quaerat illum iure ut recusandae ullam aliquam!",
        placeholder: "Description",
        label: "Description",
      },
      {
        name: "startDate",
        type: "textarea",
        key: "startDate",
        val: "05/2020",
        placeholder: "startDate",
        label: "Start Date",
      },
      {
        name: "endDate",
        type: "textarea",
        key: "endDate",
        val: "Current",
        placeholder: "endDate",
        label: "End Date",
      },
      {
        name: "location",
        type: "text",
        key: "location",
        val: "San Francisco",
        placeholder: "location",
        label: "Location",
      },
    ],
  ],

  newJob: [
    {
      name: "company",
      type: "text",
      key: "company",
      val: "Amazon",
      placeholder: "Company",
      label: "Company",
    },
    {
      name: "position",
      type: "text",
      key: "position",
      val: "Software Engineer",
      placeholder: "Position",
      label: "Position",
    },
    {
      name: "description",
      type: "textarea",
      key: "description",
      val: "Make coffee for daddy Bezos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, architecto unde, quidem magnam sint consequatur, incidunt sit itaque delectus culpa possimus excepturi iusto. Quaerat illum iure ut recusandae ullam aliquam!",
      placeholder: "Description",
      label: "Description",
    },
    {
      name: "startDate",
      type: "text",
      key: "startDate",
      val: "05/2020",
      placeholder: "startDate",
      label: "Start Date",
    },
    {
      name: "endDate",
      type: "text",
      key: "endDate",
      val: "06/2022",
      placeholder: "endDate",
      label: "End Date",
    },
    {
      name: "location",
      type: "text",
      key: "location",
      val: "San Diego",
      placeholder: "location",
      label: "Location",
    },
  ],
};
