export const sampleData = {
  personalInfo: [
    {
      name: "name",
      type: "text",
      key: "name",
      val: "Name",
      placeholder: "Enter Your Name",
      label: "Full Name",
    },
    {
      name: "phone",
      type: "tel",
      key: "phone",
      val: "(123) 456-7890",
      placeholder: "Enter Phone Number",
      label: "Phone Number",
    },
    {
      name: "email",
      type: "email",
      key: "email",
      val: "myEmail@gmail.com",
      placeholder: "Enter Email",
      label: "Email",
    },
    {
      name: "location",
      type: "text",
      key: "location",
      val: "San Diego, CA",
      placeholder: "Enter Your Location",
      label: "Location",
    },
  ],
  education: [
    [
      {
        name: "schoolName",
        type: "text",
        key: "schoolName",
        val: "UCSD",
        placeholder: "School Name",
        label: "School",
      },
      {
        name: "degree",
        type: "text",
        key: "degree",
        val: "Bachelor in Data Science",
        placeholder: "Degree",
        label: "Degree",
      },
      {
        name: "location",
        type: "text",
        key: "location",
        val: "San Diego, CA",
        placeholder: "Location",
        label: "Location",
      },
      {
        name: "startDate",
        type: "text",
        key: "startDate",
        val: "09/2020",
        placeholder: "Start Date",
        label: "Start",
      },
      {
        name: "endDate",
        type: "text",
        key: "endDate",
        val: "06/2024",
        placeholder: "End Date",
        label: "End",
      },
    ],
  ],

  newSchool: [
    {
      name: "schoolName",
      type: "text",
      key: "schoolName",
      val: "",
      placeholder: "School Name",
      label: "School",
    },
    {
      name: "degree",
      type: "text",
      key: "degree",
      val: "",
      placeholder: "Degree",
      label: "Degree",
    },
    {
      name: "startDate",
      type: "text",
      key: "startDate",
      val: "",
      placeholder: "Start Date",
      label: "Start",
    },
    {
      name: "endDate",
      type: "text",
      key: "endDate",
      val: "",
      placeholder: "End Date",
      label: "End",
    },
  ],
};
